export const GET_LISTS = "GET_LISTS";
export const GET_LIST_ITEMS = "GET_LIST_ITEMS";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const DELETE_LIST = "DELETE_LIST";
export const DELETE_LIST_ITEMS = "DELETE_LIST_ITEMS";
export const TOGGLE_ITEM_COMPLETED = "TOGGLE_ITEM_COMPLETED";
export const SET_ISLOADING = "SET_ISLOADING";
export const ERROR = "ERROR";
